[package]
name = "aymond-test"
version = "0.1.0"
edition = "2024"

[dependencies]
aymond = { version = "0.1.0", path = "../aymond" }
aymond-derive = { version = "0.1.0", path = "../aymond-derive" }
tokio = { version = "1.49.0", features = ["full"] }
